version: "3"
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.8
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - --api.insecure=true --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.file.directory=/etc/traefik/dynamic_conf
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - "~/certs:/tools/certs"
      - ./tools/traefik/config.yml:/etc/traefik/dynamic_conf/conf.yml:ro

    restart: unless-stopped
    
  music-player:
    image: tisage/mplayer:v1
    ports:
      - "80:4533"
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: "@every 1h"
      ND_LOGLEVEL: "info"
      ND_UIWELCOMEMESSAGE: "Welcome to SRI 2022 CS Project!"
      ND_DEFAULTTHEME: "Spotify-ish"
      ND_ENABLECOVERANIMATION: "true"
      ND_ENABLEDOWNLOADS: "false"
      ND_SESSIONTIMEOUT: "24h"
      ND_UILOGINBACKGROUNDURL: "https://raw.githubusercontent.com/tisage/SRI_2022/main/media_sample/SRI_2022_CS.jpg"
      # ND_BASEURL: ""
    volumes:
      - "~/mplayer/data:/data"
      - "~/mplayer/music:/music:ro"
    read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`sri2022cs.com`)"
      - "traefik.http.routers.whoami.entrypoints=web"
