version: "3"
services:
  nginx-proxy:
      image: jwilder/nginx-proxy
      container_name: nginx-proxy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/opt/nginx-proxy/certs:/etc/nginx/certs:ro"
        - "/opt/nginx-proxy/vhost.d:/etc/nginx/vhost.d:rw"
        - "/opt/nginx-proxy/htpasswd:/etc/nginx/htpasswd:ro"
        - "/var/run/docker.sock:/tmp/docker.sock:ro"
        - "/usr/share/nginx/html"
        - "/opt/nginx-proxy/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes_from:
      - nginx-proxy
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/nginx-proxy/certs:/etc/nginx/certs:rw"
      - "/opt/nginx-proxy/vhost.d:/etc/nginx/vhost.d:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    
  music-player:
    image: tisage/mplayer:v1
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: "@every 1h"
      ND_LOGLEVEL: "info"
      ND_UIWELCOMEMESSAGE: "Welcome to SRI 2022 CS Project!"
      ND_DEFAULTTHEME: "Spotify-ish"
      ND_ENABLECOVERANIMATION: "true"
      ND_ENABLEDOWNLOADS: "false"
      ND_SESSIONTIMEOUT: "24h"
      ND_UILOGINBACKGROUNDURL: "https://raw.githubusercontent.com/tisage/SRI_2022/main/media_sample/SRI_2022_CS.jpg"
      # ND_BASEURL: ""
    volumes:
      - "~/mplayer/data:/data"
      - "~/mplayer/music:/music:ro"
