version: '3.7'
# 8/1/2022 dev
# ssl supports
services:
  traefik:
    image: traefik:v2.5.2
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file=true"
      - "--providers.file.watch=true"
      #- "--providers.file.filename=/etc/traefik/rules.toml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      #- "--entrypoints.ssh.address=:22"
      #- "--entrypoints.hkps.address=:11371"
      - "--entryPoints.web.forwardedHeaders.insecure"
      - "--entryPoints.websecure.forwardedHeaders.insecure"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.email=admin@andrewzah.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redir.redirectScheme.scheme=https"

        #- "traefik.http.routers.bluemap.rule=Host(`fabric.genessee.zah.rocks`)"
        #- "traefik.http.routers.bluemap.entrypoints=websecure"
        #- "traefik.http.routers.bluemap.tls.certresolver=myresolver"
        #- "traefik.http.services.bluemap.loadbalancer.server.url=http://192.168.1.16"
        #- "traefik.http.services.bluemap.loadbalancer.server.port=8100"
    ports:
      #- "22:22"
      - "80:80"
      - "443:443"
      - "8080:8080"
      #- "11371:11371"
    volumes:
      - "~/traefik/rules.toml:/etc/traefik/rules.toml"
      - "~/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    extra_hosts:
      - host.docker.internal:192.81.214.162

  navidrome:
    image: tisage/mplayer:v1
    environment:
      ND_SCANSCHEDULE: '@every 1m'
      ND_COVERJPEGQUALITY: 85
      ND_TRANSCODINGCACHESIZE: "500MB"
      ND_LOGLEVEL: 'info'
      ND_ENABLEDOWNLOADS: 'false'
      ND_DEVACTIVITYPANEL: 'false'
      ND_AUTOIMPORTPLAYLISTS: 'false'
      ND_ENABLEGRAVATAR: 'false'
      ND_ENABLESTARRATING: 'false'
      ND_LASTFM_ENABLED: 'false'
      # disable for security
      ND_ENABLETRANSCODINGCONFIG: 'false'
      # Customize a little bit
      ND_UIWELCOMEMESSAGE: "Welcome to SRI 2022 CS Project!"
      ND_UILOGINBACKGROUNDURL: "https://raw.githubusercontent.com/tisage/SRI_2022/main/media_sample/SRI_2022_CS.jpg"

    ports:
        - "4533"
    volumes:
      - "~/mplayer/data:/data"
      - "~/mplayer/music:/music"
    restart: unless-stopped
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome.rule=Host(`sri2022cs.com`)"
      - "traefik.http.routers.navidrome.entrypoints=websecure"
      - "traefik.http.routers.navidrome.tls.certresolver=myresolver"